services:
  pipeline:
    build:
      context: ./
      dockerfile: ./images/Dockerfile
    container_name: "pipeline"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:17"
    container_name: "postgres"
    env_file: "env"
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
  dashboard:
    image: metabase/metabase
    container_name: "dashboard"
    ports:
      - "3000:3000"