services:
  pipeline:
    build:
      context: ./
      dockerfile: ./images/Dockerfile
    container_name: "pipeline"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:17"
    container_name: "postgres"
    env_file: "env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  dashboard:
    image: metabase/metabase
    container_name: "dashboard"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy